#!/bin/bash

function run {
    valgrindlog=$(mktemp --tmpdir valgrind.log.XXXXXXXXXX)
    valgrind --quiet --log-file="$valgrindlog" --error-exitcode=124 --leak-check=full --track-fds=yes ./ja2l
    status=$?
    sed -i '/FILE DESCRIPTORS: 1 open at exit./,+4 d' -- "$valgrindlog" # 1 is expected, the valgrind logfile fd
    cat >&2 -- "$valgrindlog"
    rm -f -- "$valgrindlog"
    if ((status != 0)); then
        exit 1
    fi
}

function assertEquals {
    if [[ "$1" != "$2" ]]; then
        printf >&2 '%s: assertion failure\n' "${3:-(unknown function)}"
        diff >&2 -u --label "expected" --label "actual" <(printf '%s' "$1") <(printf '%s' "$2")
        exit 1
    fi
}

function testSingleLine {
    expected='{}'
    actual=$(printf '[\n{}\n]\n' | run)
    if (($?)); then
        exit 1
    fi
    assertEquals "$expected" "$actual" "${FUNCNAME[0]}"
}

function testMultiLine {
    expected=$'{}\n{}'
    actual=$(printf '[\n{},\n{}\n]\n' | run)
    if (($?)); then
        exit 1
    fi
    assertEquals "$expected" "$actual" "${FUNCNAME[0]}"
}

testSingleLine
testMultiLine
